name: EasyBrag
main: skyss0fly\EasyBrag\Main
version: 1.1.0
api: 5.0.0
author: skyss0fly
description: A simple bragging plugin
permissions:
  EasyBrag.use:
    default: true
  EasyBrag.itemview:
    default: true
commands:
   brag:
    description: use this to brag your item
    permission: EasyBrag.use
    default: true
   itembrag:
    description: use this to brag your item
    permission: EasyBrag.use
    default: true
   itemview:
    description: use this to view an item that has been bragged
    permission: EasyBrag.itemview
    default: true
  
  
