name: EasyBrag
main: skyss0fly\EasyBrag\Main
version: 1.2.0
api: 5.0.0
author: [skyss0fly, Levonzie]
description: A simple bragging plugin
permissions:
  easybrag.use:
    default: true
  easybrag.cooldown_bypass:
    default: op
  easybrag.administrator:
  default: false
commands:
  brag:
    description: brag the item you have in your hand!
    permission: easybrag.use
    default: true
    
 disablebrag:
    description: disable brag
    permission: easybrag.administrator
    default: false
 enablebrag:
    description: enable brag
    permission: easybrag.administrator
    default: false
    

  
