name: EasyBrag
main: skyss0fly\EasyBrag\Main
version: 1.1.0
api: 5.0.0
author: skyss0fly
description: A simple bragging plugin
permissions:
  EasyBrag.use:
    default: true
commands:
  brag:
    description: use this to brag your item
    permission: EasyBrag.use
    default: true
  itemsee:
    description: use this to see current brags 
    permission: EasyBrag.see
    default: true
  
